### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by LegendofzeldaLF** [CryZe/LiveSplitOne#42]
Can We Please Have This As A Mobile App In The Appstore Please I Would Literally Pay $0-$10 Dollars For The App. So If You Good Can Please Make This A App Because I Tried Tops And It Was WAAAAAAAY Better Then My App I Have (Msplit) And I Would Be Very Grateful :D

**Comment by CryZe** [comment]
There's a mobile app in a different repo. But at the moment we are not actively working on it and are focusing on this one. Most of the code is shared between them, so the mobile app benefits from most of the development here. I think for the remainder of this year, the focus will mostly be on the main version.
