### ISSUE TITLE
Can't get it to compile on Mac OS 10.12

### ISSUE THREAD

**Issue by Yascob99** [CryZe/LiveSplitOne#59]
I tried to get it to compile after installing all the components I could find like the nightly build of Rust/Cargo and the target "asmjs-unknown-emscripten" but I can't seem to get it to compile and always get given an extremely lengthy and cryptic error:
[Debug.txt](https://github.com/CryZe/LiveSplitOne/files/1585422/Debug.txt)

Any assistance in solving this error would be appreciated or tips on compiling.

**Comment by hallcristobal** [comment]
It looks to me like you do not have the Emscripten compiler installed or it’s not in your PATH.

The incoming-64bit version is recommended. https://users.rust-lang.org/t/compiling-to-the-web-with-rust-and-emscripten/7627

**Comment by Yascob99** [comment]
Yeah, I later figured that out and did a bit more testing. I got emsdk installed and put into path using the incoming 64bit version. It still gets stuck at the same point but gives me a different error. From the looks of it it is the livesplit core causing me issues. I'm wondering if I should go onto their issues and see if they have a solution. 

Here's my current error if you were interested:
[Debug2.txt](https://github.com/CryZe/LiveSplitOne/files/1586500/Debug2.txt)

**Comment by hallcristobal** [comment]
It seems to be an issue with the current emscripten build on MacOS  https://github.com/kripken/emscripten/issues/5418
It seems like some people are having success with workarounds using homebrew. I could say try building with “latest” `email install latest` however I have not tried building livesplit-core with latest myself, and cannot guarantee it’ll work correctly.

**Comment by Yascob99** [comment]
Okay looks like I needed to a couple things to get it to work. I reinstalled emscripten via homebrew instead of using the portable. I also installed llvm-ar using homebrew as well. That seemed to fix the problem. Thanks for all the help =)!
