### ISSUE TITLE
Fix Downloading Splits

### ISSUE THREAD

**Issue by CryZe** [CryZe/LiveSplitOne#7]
Downloading splits sometimes doesn't work on Chrome and some mobile browsers. I think encoding as base64 may help there. This is one of those files that don't work on Chrome: https://cryze.github.io/LiveSplitOne/#/splits-io/fgh

**Comment by hallcristobal** [comment]
I'm not getting this issue on any of my browsers, or mobile. Potentially fixed already?

**Comment by CryZe** [comment]
Could be. Opening often also doesn't work and that's definitely not fixed. So try fixing that maybe :P

**Comment by CryZe** [comment]
Also we should download through an object url instead. I just did that for some fun little project I did and it works way better: https://github.com/CryZe/sarc-tool/blob/master/index.html#L42

**Comment by CryZe** [comment]
Chrome has a 2MiB URL limit, which is what caused this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=69227

I fixed it by now on the Run Editor branch.
